

name: build d'un projet

on:
  push:
    branches: [ "dev" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name : Téléchargement des sources || cloner le repertoire 
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: run unit tests 
      run : mvn test


